version: '3'
services:
  dbserver:
    image: helgecph/dbserver
    ports:
      - "27017:27017"
    networks:
      - outside

  webserver:
    image: helgecph/webserver
    ports:
      - "8080:8080"
    networks:
        - outside

  clidownload:
    image: appropriate/curl
    networks:
      - outside
    entrypoint: sh -c  "sleep 5 && curl http://webserver:8080"

networks:
  outside:
    external:
      name: example-network
